Links = [
    ["https://www.theguardian.com/world/rss",
     "The Guardian", "World", "Top"],
    ["https://www.theguardian.com/international/rss",
     "The Guardian", "General", "Top"],
    ["https://www.theguardian.com / uk / environment / rss",
     "The Guardian", "World", "Top"],
    ["https://www.theguardian.com/uk/money/rss",
     "The Guardian", "Business", "Top"],
    ["https://www.theguardian.com/uk/business/rss",
     "The Guardian", "Business", "Top"],
    ["https://www.theguardian.com/uk/technology/rss",
     "The Guardian", "Technology", "Top"],
    ["https://www.theguardian.com/uk/sport/rss",
     "The Guardian", "Sports", "Top"],
    ["http://feeds.reuters.com/reuters/INtopNews",
     "Reuters India", "General", "Top"],
    ["http://feeds.reuters.com/reuters/INbusinessNews",
     "Reuters India", "Business", "Top"],
    ["http://feeds.reuters.com/reuters/INbusinessNews",
     "Reuters India", "Business", "Top"],
    ["http://feeds.reuters.com/reuters/INsouthAsiaNews",
     "Reuters India", "World", "Top"],
    ["http://feeds.reuters.com/reuters/INworldNews",
     "Reuters India", "World", "Top"],
    ["http://feeds.reuters.com/reuters/INentertainmentNews",
     "Reuters India", "Entertainment", "Top"],
    ["http://feeds.reuters.com/reuters/INsportsNews",
     "Reuters India", "Sports", "Top"],
    ["http://feeds.reuters.com/reuters/INcricketNews",
     "Reuters India", "Sports", "Top"],
    ["http://feeds.reuters.com/reuters/INtechnologyNews",
     "Reuters India", "Technology", "Top"],
    ["http://feeds.reuters.com/reuters/INhealth",
     "Reuters India", "Health", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
     "New York Times", "General", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/World.xml",
     "New York Times", "World", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
     "New York Times", "Business", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
     "New York Times", "Technology", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
     "New York Times", "Sports", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
     "New York Times", "Science", "Top"],
    ["http://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
     "New York Times", "Health", "Top"],
    ["http://timesofindia.indiatimes.com/rssfeedstopstories.cms",
     "Times of India", "General", "Top"],
    ["http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
     "BBC", "Entertainment", "Top"],
    ["http://feeds.bbci.co.uk/news/technology/rss.xml",
     "BBC", "Technology", "Top"],
    ["http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
     "BBC", "Science", "Top"],
    ["http://feeds.bbci.co.uk/news/education/rss.xml",
     "BBC", "Education", "Top"],
    ["http://feeds.bbci.co.uk/news/health/rss.xml",
     "BBC", "Health", "Top"],
    ["http://feeds.bbci.co.uk/news/business/rss.xml",
     "BBC", "Business", "Top"],
    ["http://feeds.bbci.co.uk/news/politics/rss.xml",
     "BBC", "Politics", "Top"],
    ["http://feeds.bbci.co.uk/news/world/rss.xml",
     "BBC", "World", "Top"],
    ["http://feeds.bbci.co.uk/news/rss.xml",
     "BBC", "General", "Top"],
    ["http://rss.cnn.com/rss/cnn_latest.rss",
     "CNN", "General", "Latest"],
    ["http://rss.cnn.com/rss/edition_entertainment.rss",
     "CNN", "Entertainment", "Top"],
    ["http://rss.cnn.com/rss/edition_space.rss",
     "CNN", "Science", "Top"],
    ["http://rss.cnn.com/rss/edition_technology.rss",
     "CNN", "Technology", "Top"],
    ["http://rss.cnn.com/rss/edition_world.rss",
     "CNN", "World", "Top"],
    ["http://rss.cnn.com/rss/edition.rss",
     "CNN", "General", "Top"],
    ["http://feeds.mashable.com/Mashable",
     "Mashable", "Technology", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-top-stories",
     "NDTV", "General", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-world-news",
     "NDTV", "World", "Top"],
    ["https://feeds.feedburner.com/ndtvsports-cricket",
     "NDTV", "Sports", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-people",
     "NDTV", "General", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-latest",
     "NDTV", "General", "Top"],
    ["https://feeds.feedburner.com/ndtvprofit-latest",
     "NDTV", "Business", "Top"],
    ["https://feeds.feedburner.com/gadgets360-latest",
     "NDTV", "Technology", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-trending-news",
     "NDTV", "General", "Top"],
    ["https://feeds.feedburner.com/ndtvcooks-latest",
     "NDTV", "Health", "Top"],
    ["https://feeds.feedburner.com/ndtvnews-india-news",
     "NDTV", "General", "Top"],
    ["https://feeds.feedburner.com/ndtvsports-latest",
     "NDTV", "Sports", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/?service=rss",
     "The Hindu", "General", "Top"],
    ["http://www.thehindu.com/news/international/?service=rss",
     "The Hindu", "World", "Top"],
    ["http://www.thehindu.com/news/?service=rss",
     "The Hindu", "General", "Top"],
    ["http://www.thehindu.com/news/national/?service=rss",
     "The Hindu", "World", "Top"],
    ["http://www.thehindu.com/sport/?service=rss",
     "The Hindu", "Sports", "Top"],
    ["http://www.thehindu.com/sci-tech/technology/?service=rss",
     "The Hindu", "Technology", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://www.thehindu.com/business/?service=rss",
     "The Hindu", "Business", "Top"],
    ["http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
     "USA Today", "World", "Top"],
    ["http://www.deccanherald.com/rss-internal/top-stories.rss",
     "Deccan Herald", "General", "Top"],
    ["http://www.deccanherald.com/rss-internal/breaking-news.rss",
     "Deccan Herald", "General", "Top"],
    ["http://www.deccanherald.com/rss-internal/news.rss",
     "Deccan Herald", "World", "Top"],



]