Links = [
    # ["https://www.theguardian.com/world/rss",
    #  "The Guardian", "World", "Top"],
    # ["https://www.theguardian.com/international/rss",
    #  "The Guardian", "General", "Top"],
    # ["https://www.theguardian.com/uk/environment/rss",
    #  "The Guardian", "World", "Top"],
    # ["https://www.theguardian.com/uk/money/rss",
    #  "The Guardian", "Business", "Top"],
    # ["https://www.theguardian.com/uk/business/rss",
    #  "The Guardian", "Business", "Top"],
    # ["https://www.theguardian.com/uk/technology/rss",
    #  "The Guardian", "Technology", "Top"],
    # ["https://www.theguardian.com/uk/sport/rss",
    #  "The Guardian", "Sports", "Top"],
    # ["http://feeds.reuters.com/reuters/INtopNews",
    #  "Reuters India", "General", "Top"],
    # ["http://feeds.reuters.com/reuters/INbusinessNews",
    #  "Reuters India", "Business", "Top"],
    # ["http://feeds.reuters.com/reuters/INsouthAsiaNews",
    #  "Reuters India", "World", "Top"],
    # ["http://feeds.reuters.com/reuters/INworldNews",
    #  "Reuters India", "World", "Top"],
    # ["http://feeds.reuters.com/reuters/INentertainmentNews",
    #  "Reuters India", "Entertainment", "Top"],
    # ["http://feeds.reuters.com/reuters/INsportsNews",
    #  "Reuters India", "Sports", "Top"],
    # ["http://feeds.reuters.com/reuters/INcricketNews",
    #  "Reuters India", "Sports", "Top"],
    # ["http://feeds.reuters.com/reuters/INtechnologyNews",
    #  "Reuters India", "Technology", "Top"],
    # ["http://feeds.reuters.com/reuters/INhealth",
    #  "Reuters India", "Health", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    #  "New York Times", "General", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    #  "New York Times", "World", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    #  "New York Times", "Business", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    #  "New York Times", "Technology", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    #  "New York Times", "Sports", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    #  "New York Times", "Science", "Top"],
    # ["http://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    #  "New York Times", "Health", "Top"],
    # ["http://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    #  "Times of India", "General", "Top"],
    # ["http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    #  "BBC", "Entertainment", "Top"],
    # ["http://feeds.bbci.co.uk/news/technology/rss.xml",
    #  "BBC", "Technology", "Top"],
    # ["http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    #  "BBC", "Science", "Top"],
    # ["http://feeds.bbci.co.uk/news/education/rss.xml",
    #  "BBC", "Education", "Top"],
    # ["http://feeds.bbci.co.uk/news/health/rss.xml",
    #  "BBC", "Health", "Top"],
    # ["http://feeds.bbci.co.uk/news/business/rss.xml",
    #  "BBC", "Business", "Top"],
    # ["http://feeds.bbci.co.uk/news/politics/rss.xml",
    #  "BBC", "Politics", "Top"],
    # ["http://feeds.bbci.co.uk/news/world/rss.xml",
    #  "BBC", "World", "Top"],
    # ["http://feeds.bbci.co.uk/news/rss.xml",
    #  "BBC", "General", "Top"],
    # ["http://rss.cnn.com/rss/cnn_Top.rss",
    #  "CNN", "General", "Top"],
    # ["http://rss.cnn.com/rss/edition_entertainment.rss",
    #  "CNN", "Entertainment", "Top"],
    # ["http://rss.cnn.com/rss/edition_space.rss",
    #  "CNN", "Science", "Top"],
    # ["http://rss.cnn.com/rss/edition_technology.rss",
    #  "CNN", "Technology", "Top"],
    # ["http://rss.cnn.com/rss/edition_world.rss",
    #  "CNN", "World", "Top"],
    # ["http://rss.cnn.com/rss/edition.rss",
    #  "CNN", "General", "Top"],
    # ["http://feeds.mashable.com/Mashable",
    #  "Mashable", "Technology", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-top-stories",
    #  "NDTV", "General", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-world-news",
    #  "NDTV", "World", "Top"],
    # ["https://feeds.feedburner.com/ndtvsports-cricket",
    #  "NDTV", "Sports", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-people",
    #  "NDTV", "General", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-Top",
    #  "NDTV", "General", "Top"],
    # ["https://feeds.feedburner.com/ndtvprofit-Top",
    #  "NDTV", "Business", "Top"],
    # ["https://feeds.feedburner.com/gadgets360-Top",
    #  "NDTV", "Technology", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-trending-news",
    #  "NDTV", "General", "Top"],
    # ["https://feeds.feedburner.com/ndtvcooks-Top",
    #  "NDTV", "Health", "Top"],
    # ["https://feeds.feedburner.com/ndtvnews-india-news",
    #  "NDTV", "General", "Top"],
    # ["https://feeds.feedburner.com/ndtvsports-Top",
    #  "NDTV", "Sports", "Top"],
    # ["http://www.thehindu.com/business/?service=rss",
    #  "The Hindu", "Business", "Top"],
    # ["http://www.thehindu.com/?service=rss",
    #  "The Hindu", "General", "Top"],
    # ["http://www.thehindu.com/news/international/?service=rss",
    #  "The Hindu", "World", "Top"],
    # ["http://www.thehindu.com/news/?service=rss",
    #  "The Hindu", "General", "Top"],
    # ["http://www.thehindu.com/sci-tech/technology/?service=rss",
    #  "The Hindu", "Technology", "Top"],
    # ["http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
    #  "USA Today", "World", "Top"],
    # ["http://www.deccanherald.com/rss-internal/top-stories.rss",
    #  "Deccan Herald", "General", "Top"],
    # ["http://www.deccanherald.com/rss-internal/breaking-news.rss",
    #  "Deccan Herald", "General", "Top"],
    # ["http://www.deccanherald.com/rss-internal/news.rss",
    #  "Deccan Herald", "World", "Top"],
    # ["http://www.dailymail.co.uk/articles.rss",
    #  "Daily Mail", "World", "Top"],
    # ["http://www.dailymail.co.uk/home/index.rss",
    #  "Daily Mail", "World", "Top"],
    # ["http://www.dailymail.co.uk/news/index.rss",
    #  "Daily Mail", "General", "Top"],
    # ["https://www.bloombergquint.com/stories.rss",
    #  "The Quint", "General", "Top"],
    # ["https://economictimes.indiatimes.com/rssfeedsdefault.cms",
    #  "Economic Times", "General", "Top"],
    # ["https://economictimes.indiatimes.com/rssfeedstopstories.cms",
    #  "Economic Times", "General", "Top"],
    # ["https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/news/rssfeeds/1715249553.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/industry/rssfeeds/13352306.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/wealth/rssfeeds/837555174.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/jobs/rssfeeds/107115.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/ipos/fpos/rssfeeds/14655708.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/commodities/rssfeeds/1808152121.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/forex/rssfeeds/1150221130.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/bonds/rssfeeds/2146846.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/markets/market-moguls/rssfeeds/54953131.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/rsssymbolfeeds/commodityname-Gold.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/news/company/rssfeeds/2143429.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/news/economy/rssfeeds/1373380680.cms",
    #  "Economic Times", "Economy", "Top"],
    # ["https://economictimes.indiatimes.com/news/politics-and-nation/rssfeeds/1052732854.cms",
    #  "Economic Times", "India", "Top"],
    # ["https://economictimes.indiatimes.com/news/defence/rssfeeds/46687796.cms",
    #  "Economic Times", "World", "Top"],
    # ["https://economictimes.indiatimes.com/news/international/rssfeeds/858478126.cms",
    #  "Economic Times", "World", "Top"],
    # ["https://economictimes.indiatimes.com/news/india-unlimited/rssfeeds/45228216.cms",
    #  "Economic Times", "World", "Top"],
    # ["https://economictimes.indiatimes.com/news/sports/rssfeeds/26407562.cms",
    #  "Economic Times", "Sports", "Top"],
    # ["https://economictimes.indiatimes.com/news/science/rssfeeds/39872847.cms",
    #  "Economic Times", "Science", "Top"],
    # ["https://economictimes.indiatimes.com/news/environment/rssfeeds/2647163.cms",
    #  "Economic Times", "Science", "Top"],
    # ["https://www.wired.com/feed/rss",
    #  "Wired", "General", "Top"],
    # ["https://www.wired.com/feed/category/business/Top/rss",
    #  "Wired", "Business", "Top"],
    # ["https://www.wired.com/feed/category/science/Top/rss",
    #  "Wired", "Science", "Top"],
    # ["https://www.wired.com/feed/category/gear/Top/rss",
    #  "Wired", "Technology", "Top"],
    # ["https://www.wired.com/feed/category/security/Top/rss",
    #  "Wired", "Technology", "Top"],
    # ["https://www.wired.com/feed/category/transportation/Top/rss",
    #  "Wired", "Technology", "Top"],
    # ["https://www.wired.com/feed/category/photo/Top/rss",
    #  "Wired", "General", "Top"],
    # ["http://www.independent.co.uk/news/uk/rss",
    #  "Independent", "World", "Top"],
    # ["http://www.independent.co.uk/news/world/rss",
    #  "Independent", "World", "Top"],
    # ["http://www.independent.co.uk/news/business/rss",
    #  "Independent", "Business", "Top"],
    # ["http://www.independent.co.uk/news/science/rss",
    #  "Independent", "Science", "Top"],
    # ["http://www.independent.co.uk/news/rss",
    #  "Independent", "General", "Top"],
    # ["http://www.independent.co.uk/sport/rss",
    #  "Independent", "Sports", "Top"],
    # ["http://www.independent.co.uk/arts-entertainment/rss",
    #  "Independent", "Entertainment", "Top"],
    # ["http://www.independent.co.uk/arts-entertainment/films/rss",
    #  "Independent", "Entertainment", "Top"],
    # ["http://www.independent.co.uk/arts-entertainment/comedy/rss",
    #  "Independent", "Entertainment", "Top"],
    # ["http://feeds.feedburner.com/firstpost/xfJh",
    #  "First Post", "General", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    #  "Times of India", "India", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/1221656.cms",
    #  "Times of India", "General", "Latest"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    #  "Times of India", "World", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/7098551.cms",
    #  "Times of India", "World", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
    #  "Times of India", "Business", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/4719161.cms",
    #  "Times of India", "Sports", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/4719148.cms",
    #  "Times of India", "Sports", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/3908999.cms",
    #  "Times of India", "Health", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms",
    #  "Times of India", "Science", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/5880659.cms",
    #  "Times of India", "Technology", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/913168846.cms",
    #  "Times of India", "General", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/1221656.cms",
    #  "Times of India", "General", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/2647163.cms",
    #  "Times of India", "Science", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/1945062111.cms",
    #  "Times of India", "General", "Top"],
    # ["https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms",
    #  "Times of India", "Entertainment", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/30359486.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/3907412.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/2177298.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/1898274.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/1898184.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/1898272.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/671314.cms",
     "Times of India", "World", "Top"],
    ["https://timesofindia.indiatimes.com/rssfeeds/2178430.cms",
     "Times of India", "World", "Top"],



]
